In [4]:
 # 1.a. NumPy Random Vector
import numpy as np

np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 21, 15)
print("Original Array:\n", arr)

reshaped_arr = arr.reshape(3, 5)
print("Reshaped Array (3x5):\n", reshaped_arr)

print("Shape of the array:", reshaped_arr.shape)

# Replace max in each row with 0
for i in range(reshaped_arr.shape[0]):
    max_index = reshaped_arr[i].argmax()
    reshaped_arr[i][max_index] = 0

print("Modified Array (max in each row replaced with 0):\n", reshaped_arr)



Original Array:
 [13 16  1  4  4  8 10 20 19  5  7 13  2  7  8]
Reshaped Array (3x5):
 [[13 16  1  4  4]
 [ 8 10 20 19  5]
 [ 7 13  2  7  8]]
Shape of the array: (3, 5)
Modified Array (max in each row replaced with 0):
 [[13  0  1  4  4]
 [ 8 10  0 19  5]
 [ 7  0  2  7  8]]


In [3]:
# 1.b. 2D Array with 4-byte Integers
array_4x3 = np.array([[10, 20, 30],
                      [40, 50, 60],
                      [70, 80, 90],
                      [100, 110, 120]], dtype=np.int32)

print("Array:\n", array_4x3)
print("Shape:", array_4x3.shape)
print("Type:", type(array_4x3))
print("Data Type:", array_4x3.dtype)


Array:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data Type: int32


In [5]:
#  1.c. Eigenvalues and Right Eigenvectors
matrix = np.array([[3, -2],
                   [1,  0]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:\n", eigenvalues)
print("Right Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [6]:
#  1.d. Sum of Diagonal Elements
matrix = np.array([[0, 1, 2],
                   [3, 4, 5]])

diagonal_sum = np.trace(matrix)
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [7]:
# 1.e. Reshape Array without Changing Data
original_arr = np.array([[1, 2],
                         [3, 4],
                         [5, 6]])

reshaped_arr = original_arr.reshape(2, 3)
print("Reshaped Array (2x3):\n", reshaped_arr)


Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
